### ISSUE TITLE
web

### ISSUE THREAD

**Issue by despoinamusica39** [Desz01ate/ListenerX#5]
hello there!happy new year.please can you make one web to use your project?

**Comment by Desz01ate** [comment]
This app is designed to work as a desktop app because most features are intended (and rely) on desktop components, API like background wallpaper, Razer Chroma SDK which web-based can't do things like this.

**Comment by despoinamusica39** [comment]
woowwwww...but its for searching music from itunes?

**Comment by Desz01ate** [comment]
For iTunes (aka. Apple Music) the module is implement on top of Interop.iTunesLib.dll (https://github.com/Desz01ate/ListenerX/blob/master/Listener.Player.AppleMusic/Interop.iTunesLib.dll) which is a COM object that is interact directly with iTunes on Windows, it is not a REST API based but rather a way to control iTunes app from third party application, so for this kind of search you asking for may be accomplish using https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/ which is not what this project using.
